FROM php:7.4-fpm

ARG USERNAME=app
ARG UID=1000
ARG GID=1000

RUN apt-get update \
    && apt-get install -y \
    libzip-dev \
    zip

RUN docker-php-ext-install zip mysqli pdo_mysql

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

RUN groupadd -g $GID -o $USERNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $USERNAME

USER $USERNAME

CMD ["php-fpm"]