version: '3.3'
services:
  app:
    container_name: slim-app
    build:
      context: ./
      dockerfile: docker/php/dockerfile
      args:
        USERNAME: "app"
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./.env:/var/www/.env
      - ./tests:/var/www/tests
  webserver:
    container_name: slim-webserver
    image: nginx:latest
    working_dir: /var/www
    volumes:
    - ./app:/var/www
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEBSERVER_PORT}:80
    depends_on:
      - app
  database:
    container_name: slim-database
    image: mysql:5.7
    volumes:
    - database-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
  phpmyadmin:
    container_name: slim-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOST: ${MYSQL_HOST_NAME}
      PMA_USER: ${MYSQL_ROOT_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: always
    depends_on:
      - database
volumes:
  database-data: